export default {
  REQUEST: {
    LOADING: "LOADING",
    LOADING_SUCCESS: "LOADING_SUCCESS",
    LOADING_ERROR: "LOADING_ERROR"
  },
  SESSION: {
    LOAD_CURRENT_USER: "LOAD_CURRENT_USER"
  },
  FILE: {
    LOAD_REPOS: "LOAD_REPOS",
    LOAD_FILES: "LOAD_FILES"
  }
};
